import { MissionWorktree } from "../../features/mission";
import type { MissionRouteSource } from "./route-context";

export function renderMissionRoute(
  source: MissionRouteSource,
  options: { embedded?: boolean; chatOnly?: boolean } = {},
) {
  const { embedded = false, chatOnly = false } = options;
  const {
    prompt,
    promptImages,
    rpcClientRef,
    dispatch,
    socketRef,
    activeSessionId,
    draftChatWindow,
    setDraftChatWindow,
    selectedProjectId,
    selectedCwd,
    selectedAgentId,
    activeSession,
    diffs,
    historicalDiffIncompleteBySession,
    outputs,
    messages,
    sessionTimeline,
    sessionPlans,
    dismissedCompletedSessionPlanKeys,
    setDismissedCompletedSessionPlanKeys,
    toolCalls,
    statuses,
    copy,
    selectedMissionDisplayTabId,
    openedMissionDiffFilePaths,
    closeMissionDiffFile,
    activeSessionProjectId,
    projectFilesByScope,
    activeSessionProject,
    draftProject,
    selectedWorktree,
    worktrees,
    selectedDraftAgent,
    projectFileFilter,
    collapsedProjectFileDirectories,
    effectiveSidebarCollapsed,
    effectiveDisplayCollapsed,
    effectiveInspectorCollapsed,
    isMissionMobile,
    selectedMissionMobilePane,
    setSelectedMissionMobilePane,
    missionLayoutRef,
    missionLayoutStyle,
    missionSidebarCollapsed,
    missionSidebarPaneStyle,
    handleMissionTreeScroll,
    setMissionSidebarCollapsed,
    setMissionDisplayCollapsed,
    setMissionInspectorCollapsed,
    missionHelms,
    effectiveMissionHelmId,
    activeHelm,
    missionProjects,
    expandedMissionHelmIds,
    projects,
    helmConnectionStates,
    activeProfileId,
    connection,
    toggleMissionHelmNode,
    selectProject,
    missionSelectedProjectId,
    expandedMissionProjectIds,
    sessions,
    sessionCountsByProject,
    agents,
    agentConnectionInventory,
    setSelectedMissionHelmId,
    setSelectedProjectId,
    setSelectedCwd,
    setSelectedAgentId,
    setExpandedMissionProjectIds,
    setActiveSessionId,
    openSession,
    renderMissionAgentIcon,
    resolveDisplaySessionTitle,
    regenerateSessionTitle,
    regeneratingIds,
    formatRelativeTime,
    setPendingSessionCleanup,
    onCloseSessionView,
    sessionHistoryState,
    toggleMissionProjectNode,
    startMissionPaneResize,
    nudgeMissionPane,
    isMissionPaneResizing,
    missionPaneResizeVersion,
    missionChatPaneStyle,
    chatMainRef,
    handleChatMainScroll,
    pairingState,
    activeSessionMessages,
    activePromptQueue,
    promptQueues,
    expandedMessageIds,
    messageHistoryState,
    setMessageHistoryState,
    loadOlderMessages,
    toggleExpandedMessage,
    pendingPermission,
    pendingApprovals,
    technicalPanels,
    updateTechnicalPanelPreference,
    respondToPermission,
    updateQueuedPrompt,
    deleteQueuedPrompt,
    worktreePickerRef,
    worktreePickerOpen,
    setWorktreePickerOpen,
    agentPickerRef,
    agentPickerOpen,
    setAgentPickerOpen,
    selectedWorktreeName,
    draftWorktreeOptions,
    selectDraftWorktree,
    agentLocked,
    filteredAgents,
    selectDraftAgent,
    createDraftSessionForAgent,
    submitPrompt,
    slashWrapperRef,
    removePromptImage,
    imagePasteNotice,
    draftContexts,
    clearDraftContexts,
    addDraftContext,
    removeDraftContext,
    commandRetentionNotice,
    setCommandRetentionNotice,
    missionPromptRef,
    setPrompt,
    handleMissionPromptKeyDown,
    handleMissionPromptPaste,
    addPromptImageFiles,
    draftPromptPlaceholder,
    slashPopupOpen,
    filteredSlashCommands,
    slashSelectedIndex,
    applySlashCommand,
    setSlashSelectedIndex,
    openSlashCommands,
    showDraftAgentModeSelect,
    missionConfigPicker,
    setMissionConfigPicker,
    draftAgentModePickerLabel,
    draftAgentModeOptions,
    effectiveDraftAgentMode,
    updateSessionDraftPreferences,
    draftModelPlaceholder,
    draftModelPickerDisabled,
    draftModelPickerLabel,
    draftModelBaseOptions,
    resolveReasoningOptionsForModel,
    draftAllModelOptions,
    draftConfigOptions,
    effectiveDraftReasoningEffort,
    effectiveDraftModelBase,
    resolveCombinedModelValue,
    showDraftReasoningSelect,
    resolveReasoningLabel,
    draftReasoningOptions,
    deckPreferences,
    gitStatusByWorktree,
    setGitStatusByWorktree,
    gitGraphByWorktree,
    setGitGraphByWorktree,
    enhancePromptDraft,
    promptEnhancerBusy,
    setPromptEnhancerStatus,
    promptEnhancerSettings,
    cancelSession,
    missionDisplayPaneStyle,
    selectedMissionDiffFilePath,
    activityHistoryState,
    setActivityHistoryState,
    activityVisibleCounts,
    setActivityVisibleCounts,
    loadOlderActivities,
    setSelectedMissionDisplayTabId,
    missionGitErrorTabOpen,
    openMissionGitErrorTab,
    closeMissionGitErrorTab,
    openDiffDetail,
    toggleMissionDiffDirectory,
    collapsedMissionDiffDirectories,
    missionInspectorPaneStyle,
    setProjectFileFilter,
    toggleProjectFileDirectory,
    openChatSessionIds,
    setOpenChatSessionIds,
    focusedChatWindowId,
    setFocusedChatWindowId,
    navigateToView,
  } = source;
  return (
    <MissionWorktree
      embedded={embedded}
      chatOnly={chatOnly}
      prompt={prompt}
      promptImages={promptImages}
      rpcClientRef={rpcClientRef}
      dispatch={dispatch}
      socketRef={socketRef}
      activeSessionId={activeSessionId}
      draftChatWindow={draftChatWindow}
      setDraftChatWindow={setDraftChatWindow}
      openChatSessionIds={openChatSessionIds}
      setOpenChatSessionIds={setOpenChatSessionIds}
      focusedChatWindowId={focusedChatWindowId}
      setFocusedChatWindowId={setFocusedChatWindowId}
      navigateToView={navigateToView}
      onCloseSessionView={onCloseSessionView}
      selectedProjectId={selectedProjectId}
      selectedCwd={selectedCwd}
      selectedAgentId={selectedAgentId}
      activeSession={activeSession}
      diffs={diffs}
      historicalDiffIncompleteBySession={historicalDiffIncompleteBySession}
      outputs={outputs}
      messages={messages}
      sessionTimeline={sessionTimeline}
      sessionPlans={sessionPlans}
      dismissedCompletedSessionPlanKeys={dismissedCompletedSessionPlanKeys}
      setDismissedCompletedSessionPlanKeys={setDismissedCompletedSessionPlanKeys}
      toolCalls={toolCalls}
      statuses={statuses}
      copy={copy}
      selectedMissionDisplayTabId={selectedMissionDisplayTabId}
      openedMissionDiffFilePaths={openedMissionDiffFilePaths}
      closeMissionDiffFile={closeMissionDiffFile}
      activeSessionProjectId={activeSessionProjectId}
      projectFilesByScope={projectFilesByScope}
      activeSessionProject={activeSessionProject}
      draftProject={draftProject}
      selectedWorktree={selectedWorktree}
      worktrees={worktrees}
      selectedDraftAgent={selectedDraftAgent}
      projectFileFilter={projectFileFilter}
      collapsedProjectFileDirectories={collapsedProjectFileDirectories}
      effectiveSidebarCollapsed={effectiveSidebarCollapsed}
      effectiveDisplayCollapsed={effectiveDisplayCollapsed}
      effectiveInspectorCollapsed={effectiveInspectorCollapsed}
      isMissionMobile={isMissionMobile}
      selectedMissionMobilePane={selectedMissionMobilePane}
      setSelectedMissionMobilePane={setSelectedMissionMobilePane}
      missionLayoutRef={missionLayoutRef}
      missionLayoutStyle={missionLayoutStyle}
      missionSidebarCollapsed={missionSidebarCollapsed}
      missionSidebarPaneStyle={missionSidebarPaneStyle}
      handleMissionTreeScroll={handleMissionTreeScroll}
      setMissionSidebarCollapsed={setMissionSidebarCollapsed}
      setMissionDisplayCollapsed={setMissionDisplayCollapsed}
      setMissionInspectorCollapsed={setMissionInspectorCollapsed}
      missionHelms={missionHelms}
      effectiveMissionHelmId={effectiveMissionHelmId}
      activeHelm={activeHelm}
      missionProjects={missionProjects}
      expandedMissionHelmIds={expandedMissionHelmIds}
      projects={projects}
      helmConnectionStates={helmConnectionStates}
      activeProfileId={activeProfileId}
      connection={connection}
      toggleMissionHelmNode={toggleMissionHelmNode}
      selectProject={selectProject}
      missionSelectedProjectId={missionSelectedProjectId}
      expandedMissionProjectIds={expandedMissionProjectIds}
      sessions={sessions}
      sessionCountsByProject={sessionCountsByProject}
      agents={agents}
      agentConnectionInventory={agentConnectionInventory}
      setSelectedMissionHelmId={setSelectedMissionHelmId}
      setSelectedProjectId={setSelectedProjectId}
      setSelectedCwd={setSelectedCwd}
      setSelectedAgentId={setSelectedAgentId}
      setExpandedMissionProjectIds={setExpandedMissionProjectIds}
      setActiveSessionId={setActiveSessionId}
      openSession={openSession}
      renderMissionAgentIcon={renderMissionAgentIcon}
      resolveDisplaySessionTitle={resolveDisplaySessionTitle}
      regenerateSessionTitle={regenerateSessionTitle}
      regeneratingIds={regeneratingIds}
      formatRelativeTime={formatRelativeTime}
      setPendingSessionCleanup={setPendingSessionCleanup}
      sessionHistoryState={sessionHistoryState}
      toggleMissionProjectNode={toggleMissionProjectNode}
      startMissionPaneResize={startMissionPaneResize}
      nudgeMissionPane={nudgeMissionPane}
      isMissionPaneResizing={isMissionPaneResizing}
      missionPaneResizeVersion={missionPaneResizeVersion}
      missionChatPaneStyle={missionChatPaneStyle}
      chatMainRef={chatMainRef}
      handleChatMainScroll={handleChatMainScroll}
      pairingState={pairingState}
      activeSessionMessages={activeSessionMessages}
      activePromptQueue={activePromptQueue}
      promptQueues={promptQueues}
      expandedMessageIds={expandedMessageIds}
      messageHistoryState={messageHistoryState}
      setMessageHistoryState={setMessageHistoryState}
      loadOlderMessages={loadOlderMessages}
      toggleExpandedMessage={toggleExpandedMessage}
      pendingPermission={pendingPermission}
      pendingApprovals={pendingApprovals}
      technicalPanels={technicalPanels}
      updateTechnicalPanelPreference={updateTechnicalPanelPreference}
      respondToPermission={respondToPermission}
      updateQueuedPrompt={updateQueuedPrompt}
      deleteQueuedPrompt={deleteQueuedPrompt}
      worktreePickerRef={worktreePickerRef}
      worktreePickerOpen={worktreePickerOpen}
      setWorktreePickerOpen={setWorktreePickerOpen}
      agentPickerRef={agentPickerRef}
      agentPickerOpen={agentPickerOpen}
      setAgentPickerOpen={setAgentPickerOpen}
      selectedWorktreeName={selectedWorktreeName}
      draftWorktreeOptions={draftWorktreeOptions}
      selectDraftWorktree={selectDraftWorktree}
      agentLocked={agentLocked}
      filteredAgents={filteredAgents}
      selectDraftAgent={selectDraftAgent}
      createDraftSessionForAgent={createDraftSessionForAgent}
      submitPrompt={submitPrompt}
      slashWrapperRef={slashWrapperRef}
      removePromptImage={removePromptImage}
      imagePasteNotice={imagePasteNotice}
      draftContexts={draftContexts}
      clearDraftContexts={clearDraftContexts}
      addDraftContext={addDraftContext}
      removeDraftContext={removeDraftContext}
      commandRetentionNotice={commandRetentionNotice}
      setCommandRetentionNotice={setCommandRetentionNotice}
      missionPromptRef={missionPromptRef}
      setPrompt={setPrompt}
      handleMissionPromptKeyDown={handleMissionPromptKeyDown}
      handleMissionPromptPaste={handleMissionPromptPaste}
      onAddPromptImages={addPromptImageFiles}
      draftPromptPlaceholder={draftPromptPlaceholder}
      slashPopupOpen={slashPopupOpen}
      filteredSlashCommands={filteredSlashCommands}
      slashSelectedIndex={slashSelectedIndex}
      applySlashCommand={applySlashCommand}
      setSlashSelectedIndex={setSlashSelectedIndex}
      openSlashCommands={openSlashCommands}
      showDraftAgentModeSelect={showDraftAgentModeSelect}
      missionConfigPicker={missionConfigPicker}
      setMissionConfigPicker={setMissionConfigPicker}
      draftAgentModePickerLabel={draftAgentModePickerLabel}
      draftAgentModeOptions={draftAgentModeOptions}
      effectiveDraftAgentMode={effectiveDraftAgentMode}
      updateSessionDraftPreferences={updateSessionDraftPreferences}
      draftModelPlaceholder={draftModelPlaceholder}
      draftModelPickerDisabled={draftModelPickerDisabled}
      draftModelPickerLabel={draftModelPickerLabel}
      draftModelBaseOptions={draftModelBaseOptions}
      resolveReasoningOptionsForModel={resolveReasoningOptionsForModel}
      draftAllModelOptions={draftAllModelOptions}
      draftConfigOptions={draftConfigOptions}
      effectiveDraftReasoningEffort={effectiveDraftReasoningEffort}
      effectiveDraftModelBase={effectiveDraftModelBase}
      resolveCombinedModelValue={resolveCombinedModelValue}
      showDraftReasoningSelect={showDraftReasoningSelect}
      resolveReasoningLabel={resolveReasoningLabel}
      draftReasoningOptions={draftReasoningOptions}
      deckPreferences={deckPreferences}
      gitStatusByWorktree={gitStatusByWorktree}
      setGitStatusByWorktree={setGitStatusByWorktree}
      gitGraphByWorktree={gitGraphByWorktree}
      setGitGraphByWorktree={setGitGraphByWorktree}
      enhancePromptDraft={enhancePromptDraft}
      promptEnhancerBusy={promptEnhancerBusy}
      promptEnhancerStatus={promptEnhancerSettings.status}
      setPromptEnhancerStatus={setPromptEnhancerStatus}
      cancelSession={cancelSession}
      missionDisplayPaneStyle={missionDisplayPaneStyle}
      selectedMissionDiffFilePath={selectedMissionDiffFilePath}
      activityHistoryState={activityHistoryState}
      setActivityHistoryState={setActivityHistoryState}
      activityVisibleCounts={activityVisibleCounts}
      setActivityVisibleCounts={setActivityVisibleCounts}
      loadOlderActivities={loadOlderActivities}
      setSelectedMissionDisplayTabId={setSelectedMissionDisplayTabId}
      missionGitErrorTabOpen={missionGitErrorTabOpen}
      openMissionGitErrorTab={openMissionGitErrorTab}
      closeMissionGitErrorTab={closeMissionGitErrorTab}
      openDiffDetail={openDiffDetail}
      toggleMissionDiffDirectory={toggleMissionDiffDirectory}
      collapsedMissionDiffDirectories={collapsedMissionDiffDirectories}
      missionInspectorPaneStyle={missionInspectorPaneStyle}
      setProjectFileFilter={setProjectFileFilter}
      toggleProjectFileDirectory={toggleProjectFileDirectory}
    />
  );
}
