import {
  DEFAULT_LOGBOOK_VISIBLE_LIMIT,
  MissionWorktree,
} from "../../features/mission";

export function renderMissionRoute(source: any) {
  const {
    prompt,
    promptImages,
    rpcClientRef,
    dispatch,
    socketRef,
    activeSessionId,
    selectedProjectId,
    selectedCwd,
    selectedAgentId,
    activeSession,
    diffs,
    outputs,
    messages,
    toolCalls,
    statuses,
    copy,
    customMissionPanelPages,
    selectedMissionPanelPageId,
    openedMissionDiffFilePaths,
    closeMissionDiffFile,
    activeSessionProjectId,
    projectFilesByScope,
    activeSessionProject,
    draftProject,
    selectedWorktree,
    worktrees,
    selectedDraftAgent,
    projectFileFilter,
    collapsedProjectFileDirectories,
    effectiveSidebarCollapsed,
    effectiveDisplayCollapsed,
    effectiveInspectorCollapsed,
    isMissionMobile,
    selectedMissionMobilePane,
    setSelectedMissionMobilePane,
    missionLayoutRef,
    missionLayoutStyle,
    missionSidebarCollapsed,
    missionSidebarPaneStyle,
    handleMissionTreeScroll,
    setMissionSidebarCollapsed,
    setMissionDisplayCollapsed,
    setMissionInspectorCollapsed,
    missionHelms,
    effectiveMissionHelmId,
    activeHelm,
    missionProjects,
    expandedMissionHelmIds,
    projects,
    helmConnectionStates,
    activeProfileId,
    connection,
    toggleMissionHelmNode,
    missionSelectedProjectId,
    expandedMissionProjectIds,
    sessions,
    sessionCountsByProject,
    agents,
    agentConnectionInventory,
    setSelectedMissionHelmId,
    setSelectedProjectId,
    setSelectedCwd,
    setSelectedAgentId,
    setExpandedMissionProjectIds,
    setActiveSessionId,
    openSession,
    renderMissionAgentIcon,
    resolveDisplaySessionTitle,
    regenerateSessionTitle,
    regeneratingIds,
    formatRelativeTime,
    setPendingSessionCleanup,
    sessionHistoryState,
    toggleMissionProjectNode,
    startMissionPaneResize,
    nudgeMissionPane,
    missionChatPaneStyle,
    chatMainRef,
    handleChatMainScroll,
    pairingState,
    activeSessionMessages,
    activePromptQueue,
    expandedMessageIds,
    messageHistoryState,
    setMessageHistoryState,
    loadOlderMessages,
    toggleExpandedMessage,
    pendingPermission,
    pendingApprovals,
    technicalPanels,
    respondToPermission,
    updateQueuedPrompt,
    deleteQueuedPrompt,
    worktreePickerRef,
    worktreePickerOpen,
    setWorktreePickerOpen,
    agentPickerRef,
    agentPickerOpen,
    setAgentPickerOpen,
    selectedWorktreeName,
    draftWorktreeOptions,
    selectDraftWorktree,
    agentLocked,
    filteredAgents,
    selectDraftAgent,
    createDraftSessionForAgent,
    submitPrompt,
    slashWrapperRef,
    removePromptImage,
    imagePasteNotice,
    missionPromptRef,
    setPrompt,
    handleMissionPromptKeyDown,
    handleMissionPromptPaste,
    addPromptImageFiles,
    draftPromptPlaceholder,
    slashPopupOpen,
    filteredSlashCommands,
    slashSelectedIndex,
    applySlashCommand,
    setSlashSelectedIndex,
    openSlashCommands,
    showDraftAgentModeSelect,
    missionConfigPicker,
    setMissionConfigPicker,
    draftAgentModePickerLabel,
    draftAgentModeOptions,
    effectiveDraftAgentMode,
    updateSessionDraftPreferences,
    draftModelPlaceholder,
    draftModelPickerDisabled,
    draftModelPickerLabel,
    draftModelBaseOptions,
    resolveReasoningOptionsForModel,
    draftAllModelOptions,
    draftConfigOptions,
    effectiveDraftReasoningEffort,
    effectiveDraftModelBase,
    resolveCombinedModelValue,
    showDraftReasoningSelect,
    resolveReasoningLabel,
    draftReasoningOptions,
    deckPreferences,
    enhancePromptDraft,
    promptEnhancerBusy,
    cancelSession,
    missionDisplayPaneStyle,
    selectedMissionDiffFilePath,
    activityHistoryState,
    setActivityHistoryState,
    activityVisibleCounts,
    setActivityVisibleCounts,
    loadOlderActivities,
    addMissionPanelPage,
    setSelectedMissionPanelPageId,
    setDraggedMissionPanelPageId,
    dropMissionPanelPage,
    openDiffDetail,
    renameMissionPanelPage,
    moveMissionPanelPage,
    deleteMissionPanelPage,
    toggleMissionDiffDirectory,
    collapsedMissionDiffDirectories,
    missionInspectorPaneStyle,
    setProjectFileFilter,
    toggleProjectFileDirectory,
  } = source;
  return (
    <MissionWorktree
      prompt={prompt}
      promptImages={promptImages}
      rpcClientRef={rpcClientRef}
      dispatch={dispatch}
      socketRef={socketRef}
      activeSessionId={activeSessionId}
      selectedProjectId={selectedProjectId}
      selectedCwd={selectedCwd}
      selectedAgentId={selectedAgentId}
      activeSession={activeSession}
      diffs={diffs}
      outputs={outputs}
      messages={messages}
      toolCalls={toolCalls}
      statuses={statuses}
      copy={copy}
      customMissionPanelPages={customMissionPanelPages}
      selectedMissionPanelPageId={selectedMissionPanelPageId}
      openedMissionDiffFilePaths={openedMissionDiffFilePaths}
      closeMissionDiffFile={closeMissionDiffFile}
      activeSessionProjectId={activeSessionProjectId}
      projectFilesByScope={projectFilesByScope}
      activeSessionProject={activeSessionProject}
      draftProject={draftProject}
      selectedWorktree={selectedWorktree}
      worktrees={worktrees}
      selectedDraftAgent={selectedDraftAgent}
      projectFileFilter={projectFileFilter}
      collapsedProjectFileDirectories={collapsedProjectFileDirectories}
      effectiveSidebarCollapsed={effectiveSidebarCollapsed}
      effectiveDisplayCollapsed={effectiveDisplayCollapsed}
      effectiveInspectorCollapsed={effectiveInspectorCollapsed}
      isMissionMobile={isMissionMobile}
      selectedMissionMobilePane={selectedMissionMobilePane}
      setSelectedMissionMobilePane={setSelectedMissionMobilePane}
      missionLayoutRef={missionLayoutRef}
      missionLayoutStyle={missionLayoutStyle}
      missionSidebarCollapsed={missionSidebarCollapsed}
      missionSidebarPaneStyle={missionSidebarPaneStyle}
      handleMissionTreeScroll={handleMissionTreeScroll}
      setMissionSidebarCollapsed={setMissionSidebarCollapsed}
      setMissionDisplayCollapsed={setMissionDisplayCollapsed}
      setMissionInspectorCollapsed={setMissionInspectorCollapsed}
      missionHelms={missionHelms}
      effectiveMissionHelmId={effectiveMissionHelmId}
      activeHelm={activeHelm}
      missionProjects={missionProjects}
      expandedMissionHelmIds={expandedMissionHelmIds}
      projects={projects}
      helmConnectionStates={helmConnectionStates}
      activeProfileId={activeProfileId}
      connection={connection}
      toggleMissionHelmNode={toggleMissionHelmNode}
      missionSelectedProjectId={missionSelectedProjectId}
      expandedMissionProjectIds={expandedMissionProjectIds}
      sessions={sessions}
      sessionCountsByProject={sessionCountsByProject}
      agents={agents}
      agentConnectionInventory={agentConnectionInventory}
      setSelectedMissionHelmId={setSelectedMissionHelmId}
      setSelectedProjectId={setSelectedProjectId}
      setSelectedCwd={setSelectedCwd}
      setSelectedAgentId={setSelectedAgentId}
      setExpandedMissionProjectIds={setExpandedMissionProjectIds}
      setActiveSessionId={setActiveSessionId}
      openSession={openSession}
      renderMissionAgentIcon={renderMissionAgentIcon}
      resolveDisplaySessionTitle={resolveDisplaySessionTitle}
      regenerateSessionTitle={regenerateSessionTitle}
      regeneratingIds={regeneratingIds}
      formatRelativeTime={formatRelativeTime}
      setPendingSessionCleanup={setPendingSessionCleanup}
      sessionHistoryState={sessionHistoryState}
      toggleMissionProjectNode={toggleMissionProjectNode}
      startMissionPaneResize={startMissionPaneResize}
      nudgeMissionPane={nudgeMissionPane}
      missionChatPaneStyle={missionChatPaneStyle}
      chatMainRef={chatMainRef}
      handleChatMainScroll={handleChatMainScroll}
      pairingState={pairingState}
      activeSessionMessages={activeSessionMessages}
      activePromptQueue={activePromptQueue}
      expandedMessageIds={expandedMessageIds}
      messageHistoryState={messageHistoryState}
      setMessageHistoryState={setMessageHistoryState}
      loadOlderMessages={loadOlderMessages}
      toggleExpandedMessage={toggleExpandedMessage}
      pendingPermission={pendingPermission}
      pendingApprovals={pendingApprovals}
      technicalPanels={technicalPanels}
      respondToPermission={respondToPermission}
      updateQueuedPrompt={updateQueuedPrompt}
      deleteQueuedPrompt={deleteQueuedPrompt}
      worktreePickerRef={worktreePickerRef}
      worktreePickerOpen={worktreePickerOpen}
      setWorktreePickerOpen={setWorktreePickerOpen}
      agentPickerRef={agentPickerRef}
      agentPickerOpen={agentPickerOpen}
      setAgentPickerOpen={setAgentPickerOpen}
      selectedWorktreeName={selectedWorktreeName}
      draftWorktreeOptions={draftWorktreeOptions}
      selectDraftWorktree={selectDraftWorktree}
      agentLocked={agentLocked}
      filteredAgents={filteredAgents}
      selectDraftAgent={selectDraftAgent}
      createDraftSessionForAgent={createDraftSessionForAgent}
      submitPrompt={submitPrompt}
      slashWrapperRef={slashWrapperRef}
      removePromptImage={removePromptImage}
      imagePasteNotice={imagePasteNotice}
      missionPromptRef={missionPromptRef}
      setPrompt={setPrompt}
      handleMissionPromptKeyDown={handleMissionPromptKeyDown}
      handleMissionPromptPaste={handleMissionPromptPaste}
      onAddPromptImages={addPromptImageFiles}
      draftPromptPlaceholder={draftPromptPlaceholder}
      slashPopupOpen={slashPopupOpen}
      filteredSlashCommands={filteredSlashCommands}
      slashSelectedIndex={slashSelectedIndex}
      applySlashCommand={applySlashCommand}
      setSlashSelectedIndex={setSlashSelectedIndex}
      openSlashCommands={openSlashCommands}
      showDraftAgentModeSelect={showDraftAgentModeSelect}
      missionConfigPicker={missionConfigPicker}
      setMissionConfigPicker={setMissionConfigPicker}
      draftAgentModePickerLabel={draftAgentModePickerLabel}
      draftAgentModeOptions={draftAgentModeOptions}
      effectiveDraftAgentMode={effectiveDraftAgentMode}
      updateSessionDraftPreferences={updateSessionDraftPreferences}
      draftModelPlaceholder={draftModelPlaceholder}
      draftModelPickerDisabled={draftModelPickerDisabled}
      draftModelPickerLabel={draftModelPickerLabel}
      draftModelBaseOptions={draftModelBaseOptions}
      resolveReasoningOptionsForModel={resolveReasoningOptionsForModel}
      draftAllModelOptions={draftAllModelOptions}
      draftConfigOptions={draftConfigOptions}
      effectiveDraftReasoningEffort={effectiveDraftReasoningEffort}
      effectiveDraftModelBase={effectiveDraftModelBase}
      resolveCombinedModelValue={resolveCombinedModelValue}
      showDraftReasoningSelect={showDraftReasoningSelect}
      resolveReasoningLabel={resolveReasoningLabel}
      draftReasoningOptions={draftReasoningOptions}
      deckPreferences={deckPreferences}
      enhancePromptDraft={enhancePromptDraft}
      promptEnhancerBusy={promptEnhancerBusy}
      cancelSession={cancelSession}
      missionDisplayPaneStyle={missionDisplayPaneStyle}
      selectedMissionDiffFilePath={selectedMissionDiffFilePath}
      activityHistoryState={activityHistoryState}
      setActivityHistoryState={setActivityHistoryState}
      activityVisibleCounts={activityVisibleCounts}
      setActivityVisibleCounts={setActivityVisibleCounts}
      loadOlderActivities={loadOlderActivities}
      addMissionPanelPage={addMissionPanelPage}
      setSelectedMissionPanelPageId={setSelectedMissionPanelPageId}
      setDraggedMissionPanelPageId={setDraggedMissionPanelPageId}
      dropMissionPanelPage={dropMissionPanelPage}
      openDiffDetail={openDiffDetail}
      renameMissionPanelPage={renameMissionPanelPage}
      moveMissionPanelPage={moveMissionPanelPage}
      deleteMissionPanelPage={deleteMissionPanelPage}
      toggleMissionDiffDirectory={toggleMissionDiffDirectory}
      collapsedMissionDiffDirectories={collapsedMissionDiffDirectories}
      missionInspectorPaneStyle={missionInspectorPaneStyle}
      setProjectFileFilter={setProjectFileFilter}
      toggleProjectFileDirectory={toggleProjectFileDirectory}
      defaultLogbookVisibleLimit={DEFAULT_LOGBOOK_VISIBLE_LIMIT}
    />
  );
}
