export const DEFAULT_PROMPT = "";
export const DEFAULT_SESSION_PAGE_LIMIT = 25;
export const DEFAULT_MESSAGE_PAGE_LIMIT = 20;
export const DEFAULT_ACTIVITY_PAGE_LIMIT = 50;
export const DEFAULT_LOGBOOK_VISIBLE_LIMIT = 25;
