export const UI_COPY = {
  "zh-CN": {
    localeLabel: "中文",
    heroEyebrow: "ACP Coding Agent 舰队指挥甲板",
    heroBody:
      "一个同源内置 Deck，管理当前 Tiller 的项目、工作区与 ACP 舰员。先选项目，再进入该项目下的任务，会话成立后 ACP 舰员会被锁定。",
    connection: {
      connecting: "连接中",
      connected: "已连接",
      disconnected: "已断开",
    },
    daemonAddress: "Helm 地址",
    daemonPort: "端口",
    connectDaemon: "连接 Helm",
    reconnectDaemon: "重新连接",
    connectHint:
      "先填写你的 Helm 地址和端口，再主动连接。连接成功后才进入配对流程。",
    connectFeedbackIdle: "尚未连接 Helm。",
    connectFeedbackConnecting: "正在连接 Helm...",
    pairingTitle: "设备配对",
    pairingHint: "连接成功后，请输入 Helm 终端显示的 6 位配对码。",
    pairingFeedbackIdle: "等待输入配对码。",
    pairingDebug: "调试回显",
    controlPlane: "指挥甲板",
    testConfiguredAgent: "测试当前舰员",
    createSession: "创建任务",
    selectedWorktree: "工作区",
    selectedAgent: "舰员",
    worktrees: "工作区",
    agents: "ACP 舰员",
    noWorktrees: "暂无工作区",
    noAgents: "暂无舰员",
    addAgentDraft: "添加 ACP 舰员配置",
    saveDraftLocal: "保存本地配置草稿",
    writeDaemonConfig: "写入 Helm 配置",
    name: "名称",
    command: "命令",
    arguments: "参数",
    draftOnlyTitle: "本地配置草稿",
    draftOnlyHint:
      "可先录入一个真实 ACP 舰员 command 组合，例如 `opencode acp --pure`，确认无误后再写入 Helm 配置。",
    daemonConfigTitle: "写入 Helm 配置",
    daemonConfigHint:
      "这里会向 `~/.config/tiller/config.json` 写入舰员 provider 条目。建议先测试当前舰员命令可用。",
    hooksTitle: "ACP 归一化层",
    hooksBody:
      "runtime 会把 session/update 尽量归一化为消息、权限请求、航行日志与 diff 事件，便于不同 ACP 舰员共用同一套 UI。",
    agentTestTitle: "舰员测试",
    sessions: "任务",
    totalSuffix: "个",
    noSessions: "先创建一个任务开始控制环路。",
    sessionDetail: "任务详情",
    noActiveSession: "还没有活跃任务。",
    cancelSession: "取消任务",
    cleanupSession: "清理任务",
    promptPlaceholder: "向当前任务下达指令",
    sendPrompt: "发送提示词",
    agentStream: "舰员消息流",
    commandOutput: "航行日志",
    diffSummary: "变更摘要",
    waitingForAgent: "等待舰员活动中。",
    permissionRequest: "权限请求",
    allowOnce: "本次允许",
    deny: "拒绝",
    noCommandOutput: "航行日志暂无记录。",
    noDiffSummary: "还没有文件变更。",
    role: {
      assistant: "助手",
      system: "系统",
      user: "你",
    },
    status: {
      starting: "启动中",
      running: "运行中",
      waiting_for_permission: "等待审批",
      idle: "空闲",
      error: "错误",
      cancelled: "已取消",
    },
    draftLoaded: "已从浏览器本地存储加载配置草稿。",
    draftParseFailed: "本地配置草稿解析失败，已回退到默认 ACP 配置。",
    savedDraft: "已保存本地配置草稿：",
    writingConfig: "正在写入舰员 provider 到 Helm 配置...",
    testRunningPrefix: "正在测试",
  },
} as const;

export type Locale = keyof typeof UI_COPY;
