import { OverviewPage } from "../features/overview/ui/page";
import { AgentsPage } from "../features/agents/ui/page";
import { SettingsPage } from "../features/settings/ui/page";
import { MissionWorkspace } from "../features/mission/ui/workspace";
import { DEFAULT_DAEMON_HOST, DEFAULT_DAEMON_PORT, DEFAULT_LOGBOOK_VISIBLE_LIMIT, IS_EMBEDDED_HELM_DECK } from "./app-constants";
export function AppRoutes({ ctx }: { ctx: any }) {
  const source = {
    ...ctx.runtimeState, ...ctx.deckData, ...ctx.missionView, ...ctx.appActions,
    ...ctx.controllers, ...ctx.panelPages, ...ctx.selection, ...ctx.layout,
    ...ctx.history, ...ctx.preferenceActions, ...ctx.promptEnhancerSettings,
    ...ctx.slash, ...ctx.codeActions, ...ctx.helmConnection, ...ctx,
  };
  const {
    activeView,
    copy,
    connection,
    activeHelm,
    daemonHost,
    daemonPort,
    projects,
    workspaces,
    agents,
    sessions,
    navigateToView,
    openSession,
    resolveDisplaySessionTitle,
    formatRelativeTime,
    prompt,
    promptImages,
    socketRef,
    activeSessionId,
    selectedProjectId,
    selectedWorkspaceId,
    selectedAgentId,
    activeSession,
    diffs,
    outputs,
    toolCalls,
    statuses,
    customMissionPanelPages,
    selectedMissionPanelPageId,
    activeSessionProjectId,
    projectFilesByScope,
    activeSessionProject,
    draftProject,
    selectedWorkspace,
    selectedDraftAgent,
    projectFileFilter,
    collapsedProjectFileDirectories,
    effectiveSidebarCollapsed,
    effectiveInspectorCollapsed,
    missionLayoutRef,
    missionLayoutStyle,
    missionSidebarCollapsed,
    missionSidebarPaneStyle,
    handleMissionTreeScroll,
    setMissionSidebarCollapsed,
    missionHelms,
    effectiveMissionHelmId,
    missionProjects,
    expandedMissionHelmIds,
    helmConnectionStates,
    activeProfileId,
    toggleMissionHelmNode,
    missionSelectedProjectId,
    expandedMissionProjectIds,
    sessionCountsByProject,
    setSelectedMissionHelmId,
    setSelectedProjectId,
    setSelectedWorkspaceId,
    setSelectedAgentId,
    setExpandedMissionProjectIds,
    setActiveSessionId,
    renderMissionAgentIcon,
    setPendingSessionCleanup,
    sessionHistoryState,
    toggleMissionProjectNode,
    startMissionPaneResize,
    nudgeMissionPane,
    missionChatPaneStyle,
    chatMainRef,
    handleChatMainScroll,
    pairingState,
    activeSessionMessages,
    expandedMessageIds,
    messageHistoryState,
    loadOlderMessages,
    toggleExpandedMessage,
    pendingPermission,
    technicalPanels,
    respondToPermission,
    worktreePickerRef,
    worktreePickerOpen,
    setWorktreePickerOpen,
    agentPickerRef,
    agentPickerOpen,
    setAgentPickerOpen,
    selectedWorkspaceName,
    draftWorkspaceOptions,
    selectDraftWorkspace,
    agentLocked,
    filteredAgents,
    selectDraftAgent,
    submitPrompt,
    slashWrapperRef,
    removePromptImage,
    imagePasteNotice,
    missionPromptRef,
    setPrompt,
    handleMissionPromptKeyDown,
    handleMissionPromptPaste,
    draftPromptPlaceholder,
    slashPopupOpen,
    filteredSlashCommands,
    slashSelectedIndex,
    applySlashCommand,
    setSlashSelectedIndex,
    showDraftAgentModeSelect,
    missionConfigPicker,
    setMissionConfigPicker,
    draftAgentModePickerLabel,
    draftAgentModeOptions,
    effectiveDraftAgentMode,
    updateSessionDraftPreferences,
    draftModelPlaceholder,
    draftModelPickerDisabled,
    draftModelPickerLabel,
    draftModelBaseOptions,
    resolveReasoningOptionsForModel,
    draftAllModelOptions,
    draftConfigOptions,
    effectiveDraftReasoningEffort,
    effectiveDraftModelBase,
    resolveCombinedModelValue,
    showDraftReasoningSelect,
    resolveReasoningLabel,
    draftReasoningOptions,
    deckPreferences,
    enhancePromptDraft,
    promptEnhancerBusy,
    cancelSession,
    missionDisplayPaneStyle,
    selectedMissionDiffFilePath,
    messages,
    activityHistoryState,
    activityVisibleCounts,
    setActivityVisibleCounts,
    loadOlderActivities,
    addMissionPanelPage,
    setSelectedMissionPanelPageId,
    setDraggedMissionPanelPageId,
    dropMissionPanelPage,
    openDiffDetail,
    renameMissionPanelPage,
    moveMissionPanelPage,
    deleteMissionPanelPage,
    toggleMissionDiffDirectory,
    missionInspectorPaneStyle,
    setProjectFileFilter,
    setMissionInspectorCollapsed,
    toggleProjectFileDirectory,
    daemonProfiles,
    selectedHelmKey,
    helmInventories,
    trustedDevices,
    helmSocketRefs,
    configuredHelms,
    fleetAddHelmStage,
    fleetAddHelmModalOpen,
    closeFleetAddHelmModal,
    connectFromFleetAddHelmModal,
    fleetAddHelmName,
    setFleetAddHelmName,
    fleetAddHelmHost,
    setFleetAddHelmHost,
    fleetAddHelmPort,
    setFleetAddHelmPort,
    submitPairingCode,
    pairInputRefs,
    pairingCodeInput,
    updatePairingDigit,
    handlePairingKeyDown,
    pastePairingDigits,
    sendPairingRequest,
    connectToDaemon,
    pendingHelmDeleteProfile,
    setPendingHelmDeleteProfile,
    removeDaemonProfile,
    selectHelmKey,
    openFleetAddHelmModal,
    manualDisconnectRef,
    setConnection,
    lastFilesScopeKeyRef,
    setHelmConnectionState,
    connectDaemonProfile,
    fleetProjectFormOpen,
    setFleetProjectFormOpen,
    fleetProjectDraft,
    setFleetProjectDraft,
    setFleetProjectSaveMessage,
    fleetProjectSaveMessage,
    fleetAgentFormOpen,
    setFleetAgentFormOpen,
    fleetAgentDraft,
    setFleetAgentDraft,
    requestCounter,
    renderTrustedDevicesPanel,
    promptModelPickerRef,
    promptEnhancerModelPickerOpen,
    promptEnhancerModelFilter,
    promptEnhancerModels,
    promptEnhancerStatus,
    resetDeckPreferences,
    updateDeckPreference,
    updateTechnicalPanelPreference,
    updatePromptEnhancerLlmPreference,
    updatePromptEnhancerModelInput,
    setPromptEnhancerModelPickerOpen,
    refreshPromptEnhancerModels,
    setPromptEnhancerModelFilter,
    selectPromptEnhancerModel,
    resetPromptEnhancerDefaults,
    testPromptEnhancerSelectedModel,
  } = source;
function renderOverview() {
  return (
    <OverviewPage
      copy={copy}
      connection={connection}
      activeHelm={activeHelm}
      daemonHost={daemonHost}
      daemonPort={daemonPort}
      defaultDaemonHost={DEFAULT_DAEMON_HOST}
      defaultDaemonPort={DEFAULT_DAEMON_PORT}
      projects={projects}
      workspaces={workspaces}
      agents={agents}
      sessions={sessions}
      onNavigate={navigateToView}
      onOpenSession={openSession}
      resolveDisplaySessionTitle={resolveDisplaySessionTitle}
      formatRelativeTime={formatRelativeTime}
    />
  );
}
function renderSessions() {
  return (
    <MissionWorkspace
      prompt={prompt}
      promptImages={promptImages}
      socketRef={socketRef}
      activeSessionId={activeSessionId}
      selectedProjectId={selectedProjectId}
      selectedWorkspaceId={selectedWorkspaceId}
      selectedAgentId={selectedAgentId}
      activeSession={activeSession}
      diffs={diffs}
      outputs={outputs}
      toolCalls={toolCalls}
      statuses={statuses}
      copy={copy}
      customMissionPanelPages={customMissionPanelPages}
      selectedMissionPanelPageId={selectedMissionPanelPageId}
      activeSessionProjectId={activeSessionProjectId}
      projectFilesByScope={projectFilesByScope}
      activeSessionProject={activeSessionProject}
      draftProject={draftProject}
      selectedWorkspace={selectedWorkspace}
      selectedDraftAgent={selectedDraftAgent}
      projectFileFilter={projectFileFilter}
      collapsedProjectFileDirectories={collapsedProjectFileDirectories}
      effectiveSidebarCollapsed={effectiveSidebarCollapsed}
      effectiveInspectorCollapsed={effectiveInspectorCollapsed}
      missionLayoutRef={missionLayoutRef}
      missionLayoutStyle={missionLayoutStyle}
      missionSidebarCollapsed={missionSidebarCollapsed}
      missionSidebarPaneStyle={missionSidebarPaneStyle}
      handleMissionTreeScroll={handleMissionTreeScroll}
      setMissionSidebarCollapsed={setMissionSidebarCollapsed}
      missionHelms={missionHelms}
      effectiveMissionHelmId={effectiveMissionHelmId}
      activeHelm={activeHelm}
      missionProjects={missionProjects}
      expandedMissionHelmIds={expandedMissionHelmIds}
      projects={projects}
      helmConnectionStates={helmConnectionStates}
      activeProfileId={activeProfileId}
      connection={connection}
      toggleMissionHelmNode={toggleMissionHelmNode}
      missionSelectedProjectId={missionSelectedProjectId}
      expandedMissionProjectIds={expandedMissionProjectIds}
      sessions={sessions}
      sessionCountsByProject={sessionCountsByProject}
      agents={agents}
      setSelectedMissionHelmId={setSelectedMissionHelmId}
      setSelectedProjectId={setSelectedProjectId}
      setSelectedWorkspaceId={setSelectedWorkspaceId}
      setSelectedAgentId={setSelectedAgentId}
      setExpandedMissionProjectIds={setExpandedMissionProjectIds}
      setActiveSessionId={setActiveSessionId}
      openSession={openSession}
      renderMissionAgentIcon={renderMissionAgentIcon}
      resolveDisplaySessionTitle={resolveDisplaySessionTitle}
      formatRelativeTime={formatRelativeTime}
      setPendingSessionCleanup={setPendingSessionCleanup}
      sessionHistoryState={sessionHistoryState}
      toggleMissionProjectNode={toggleMissionProjectNode}
      startMissionPaneResize={startMissionPaneResize}
      nudgeMissionPane={nudgeMissionPane}
      missionChatPaneStyle={missionChatPaneStyle}
      chatMainRef={chatMainRef}
      handleChatMainScroll={handleChatMainScroll}
      pairingState={pairingState}
      activeSessionMessages={activeSessionMessages}
      expandedMessageIds={expandedMessageIds}
      messageHistoryState={messageHistoryState}
      loadOlderMessages={loadOlderMessages}
      toggleExpandedMessage={toggleExpandedMessage}
      pendingPermission={pendingPermission}
      technicalPanels={technicalPanels}
      respondToPermission={respondToPermission}
      worktreePickerRef={worktreePickerRef}
      worktreePickerOpen={worktreePickerOpen}
      setWorktreePickerOpen={setWorktreePickerOpen}
      agentPickerRef={agentPickerRef}
      agentPickerOpen={agentPickerOpen}
      setAgentPickerOpen={setAgentPickerOpen}
      selectedWorkspaceName={selectedWorkspaceName}
      draftWorkspaceOptions={draftWorkspaceOptions}
      selectDraftWorkspace={selectDraftWorkspace}
      agentLocked={agentLocked}
      filteredAgents={filteredAgents}
      selectDraftAgent={selectDraftAgent}
      submitPrompt={submitPrompt}
      slashWrapperRef={slashWrapperRef}
      removePromptImage={removePromptImage}
      imagePasteNotice={imagePasteNotice}
      missionPromptRef={missionPromptRef}
      setPrompt={setPrompt}
      handleMissionPromptKeyDown={handleMissionPromptKeyDown}
      handleMissionPromptPaste={handleMissionPromptPaste}
      draftPromptPlaceholder={draftPromptPlaceholder}
      slashPopupOpen={slashPopupOpen}
      filteredSlashCommands={filteredSlashCommands}
      slashSelectedIndex={slashSelectedIndex}
      applySlashCommand={applySlashCommand}
      setSlashSelectedIndex={setSlashSelectedIndex}
      showDraftAgentModeSelect={showDraftAgentModeSelect}
      missionConfigPicker={missionConfigPicker}
      setMissionConfigPicker={setMissionConfigPicker}
      draftAgentModePickerLabel={draftAgentModePickerLabel}
      draftAgentModeOptions={draftAgentModeOptions}
      effectiveDraftAgentMode={effectiveDraftAgentMode}
      updateSessionDraftPreferences={updateSessionDraftPreferences}
      draftModelPlaceholder={draftModelPlaceholder}
      draftModelPickerDisabled={draftModelPickerDisabled}
      draftModelPickerLabel={draftModelPickerLabel}
      draftModelBaseOptions={draftModelBaseOptions}
      resolveReasoningOptionsForModel={resolveReasoningOptionsForModel}
      draftAllModelOptions={draftAllModelOptions}
      draftConfigOptions={draftConfigOptions}
      effectiveDraftReasoningEffort={effectiveDraftReasoningEffort}
      effectiveDraftModelBase={effectiveDraftModelBase}
      resolveCombinedModelValue={resolveCombinedModelValue}
      showDraftReasoningSelect={showDraftReasoningSelect}
      resolveReasoningLabel={resolveReasoningLabel}
      draftReasoningOptions={draftReasoningOptions}
      deckPreferences={deckPreferences}
      enhancePromptDraft={enhancePromptDraft}
      promptEnhancerBusy={promptEnhancerBusy}
      cancelSession={cancelSession}
      missionDisplayPaneStyle={missionDisplayPaneStyle}
      selectedMissionDiffFilePath={selectedMissionDiffFilePath}
      messages={messages}
      activityHistoryState={activityHistoryState}
      activityVisibleCounts={activityVisibleCounts}
      setActivityVisibleCounts={setActivityVisibleCounts}
      loadOlderActivities={loadOlderActivities}
      addMissionPanelPage={addMissionPanelPage}
      setSelectedMissionPanelPageId={setSelectedMissionPanelPageId}
      setDraggedMissionPanelPageId={setDraggedMissionPanelPageId}
      dropMissionPanelPage={dropMissionPanelPage}
      openDiffDetail={openDiffDetail}
      renameMissionPanelPage={renameMissionPanelPage}
      moveMissionPanelPage={moveMissionPanelPage}
      deleteMissionPanelPage={deleteMissionPanelPage}
      toggleMissionDiffDirectory={toggleMissionDiffDirectory}
      missionInspectorPaneStyle={missionInspectorPaneStyle}
      setProjectFileFilter={setProjectFileFilter}
      setMissionInspectorCollapsed={setMissionInspectorCollapsed}
      toggleProjectFileDirectory={toggleProjectFileDirectory}
      defaultLogbookVisibleLimit={DEFAULT_LOGBOOK_VISIBLE_LIMIT}
    />
  );
}
function renderAgents() {
  return (
    <AgentsPage
      daemonHost={daemonHost}
      daemonPort={daemonPort}
      defaultDaemonHost={DEFAULT_DAEMON_HOST}
      defaultDaemonPort={DEFAULT_DAEMON_PORT}
      isEmbeddedHelmDeck={IS_EMBEDDED_HELM_DECK}
      daemonProfiles={daemonProfiles}
      selectedHelmKey={selectedHelmKey}
      connection={connection}
      helmConnectionStates={helmConnectionStates}
      helmInventories={helmInventories}
      trustedDevices={trustedDevices}
      projects={projects}
      agents={agents}
      workspaces={workspaces}
      socketRef={socketRef}
      helmSocketRefs={helmSocketRefs}
      configuredHelms={configuredHelms}
      fleetAddHelmStage={fleetAddHelmStage}
      fleetAddHelmModalOpen={fleetAddHelmModalOpen}
      closeFleetAddHelmModal={closeFleetAddHelmModal}
      connectFromFleetAddHelmModal={connectFromFleetAddHelmModal}
      fleetAddHelmName={fleetAddHelmName}
      setFleetAddHelmName={setFleetAddHelmName}
      fleetAddHelmHost={fleetAddHelmHost}
      setFleetAddHelmHost={setFleetAddHelmHost}
      fleetAddHelmPort={fleetAddHelmPort}
      setFleetAddHelmPort={setFleetAddHelmPort}
      submitPairingCode={submitPairingCode}
      pairInputRefs={pairInputRefs}
      pairingCodeInput={pairingCodeInput}
      pairingState={pairingState}
      updatePairingDigit={updatePairingDigit}
      handlePairingKeyDown={handlePairingKeyDown}
      pastePairingDigits={pastePairingDigits}
      sendPairingRequest={sendPairingRequest}
      connectToDaemon={connectToDaemon}
      pendingHelmDeleteProfile={pendingHelmDeleteProfile}
      setPendingHelmDeleteProfile={setPendingHelmDeleteProfile}
      removeDaemonProfile={removeDaemonProfile}
      setSelectedHelmKey={selectHelmKey}
      openFleetAddHelmModal={openFleetAddHelmModal}
      manualDisconnectRef={manualDisconnectRef}
      setConnection={setConnection}
      lastFilesScopeKeyRef={lastFilesScopeKeyRef}
      setHelmConnectionState={setHelmConnectionState}
      connectDaemonProfile={connectDaemonProfile}
      fleetProjectFormOpen={fleetProjectFormOpen}
      setFleetProjectFormOpen={setFleetProjectFormOpen}
      fleetProjectDraft={fleetProjectDraft}
      setFleetProjectDraft={setFleetProjectDraft}
      setFleetProjectSaveMessage={setFleetProjectSaveMessage}
      fleetProjectSaveMessage={fleetProjectSaveMessage}
      fleetAgentFormOpen={fleetAgentFormOpen}
      setFleetAgentFormOpen={setFleetAgentFormOpen}
      fleetAgentDraft={fleetAgentDraft}
      setFleetAgentDraft={setFleetAgentDraft}
      requestCounter={requestCounter}
      copy={copy}
      renderTrustedDevicesPanel={renderTrustedDevicesPanel}
    />
  );
}
function renderSettings() {
  return (
    <SettingsPage
      deckPreferences={deckPreferences}
      technicalPanels={technicalPanels}
      promptModelPickerRef={promptModelPickerRef}
      promptEnhancerBusy={promptEnhancerBusy}
      promptEnhancerModelPickerOpen={promptEnhancerModelPickerOpen}
      promptEnhancerModelFilter={promptEnhancerModelFilter}
      promptEnhancerModels={promptEnhancerModels}
      promptEnhancerStatus={promptEnhancerStatus}
      resetDeckPreferences={resetDeckPreferences}
      updateDeckPreference={updateDeckPreference}
      updateTechnicalPanelPreference={updateTechnicalPanelPreference}
      updatePromptEnhancerLlmPreference={updatePromptEnhancerLlmPreference}
      updatePromptEnhancerModelInput={updatePromptEnhancerModelInput}
      setPromptEnhancerModelPickerOpen={setPromptEnhancerModelPickerOpen}
      refreshPromptEnhancerModels={refreshPromptEnhancerModels}
      setPromptEnhancerModelFilter={setPromptEnhancerModelFilter}
      selectPromptEnhancerModel={selectPromptEnhancerModel}
      resetPromptEnhancerDefaults={resetPromptEnhancerDefaults}
      testPromptEnhancerSelectedModel={testPromptEnhancerSelectedModel}
    />
  );
}
  return (
    <div className="page-content stack-gap">
      {activeView === "overview" && renderOverview()}
      {activeView === "sessions" && renderSessions()}
      {activeView === "agents" && renderAgents()}
      {activeView === "settings" && renderSettings()}
    </div>
  );
}
